apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-rahul

spec:
  replicas: 5

  selector:
    matchLabels:
      app: nginx-rahul

  template:
    metadata:
      labels:
        app: nginx-rahul

    spec:
      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80